# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.22

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Produce verbose output by default.
VERBOSE = 1

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /snap/cmake/1000/bin/cmake

# The command to remove a file.
RM = /snap/cmake/1000/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/jh/repos/RacingmaybeCpp

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/jh/repos/RacingmaybeCpp

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/snap/cmake/1000/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/snap/cmake/1000/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components
.PHONY : list_install_components/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/snap/cmake/1000/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/snap/cmake/1000/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/snap/cmake/1000/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/snap/cmake/1000/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local/fast

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/snap/cmake/1000/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/snap/cmake/1000/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/jh/repos/RacingmaybeCpp/CMakeFiles /home/jh/repos/RacingmaybeCpp//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/jh/repos/RacingmaybeCpp/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named Racingmaybe

# Build rule for target.
Racingmaybe: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 Racingmaybe
.PHONY : Racingmaybe

# fast build rule for target.
Racingmaybe/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Racingmaybe.dir/build.make CMakeFiles/Racingmaybe.dir/build
.PHONY : Racingmaybe/fast

#=============================================================================
# Target rules for targets named uninstall

# Build rule for target.
uninstall: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 uninstall
.PHONY : uninstall

# fast build rule for target.
uninstall/fast:
	$(MAKE) $(MAKESILENT) -f Libraries/glfw-3.3.6/CMakeFiles/uninstall.dir/build.make Libraries/glfw-3.3.6/CMakeFiles/uninstall.dir/build
.PHONY : uninstall/fast

#=============================================================================
# Target rules for targets named update_mappings

# Build rule for target.
update_mappings: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 update_mappings
.PHONY : update_mappings

# fast build rule for target.
update_mappings/fast:
	$(MAKE) $(MAKESILENT) -f Libraries/glfw-3.3.6/src/CMakeFiles/update_mappings.dir/build.make Libraries/glfw-3.3.6/src/CMakeFiles/update_mappings.dir/build
.PHONY : update_mappings/fast

#=============================================================================
# Target rules for targets named glfw

# Build rule for target.
glfw: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 glfw
.PHONY : glfw

# fast build rule for target.
glfw/fast:
	$(MAKE) $(MAKESILENT) -f Libraries/glfw-3.3.6/src/CMakeFiles/glfw.dir/build.make Libraries/glfw-3.3.6/src/CMakeFiles/glfw.dir/build
.PHONY : glfw/fast

#=============================================================================
# Target rules for targets named boing

# Build rule for target.
boing: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 boing
.PHONY : boing

# fast build rule for target.
boing/fast:
	$(MAKE) $(MAKESILENT) -f Libraries/glfw-3.3.6/examples/CMakeFiles/boing.dir/build.make Libraries/glfw-3.3.6/examples/CMakeFiles/boing.dir/build
.PHONY : boing/fast

#=============================================================================
# Target rules for targets named gears

# Build rule for target.
gears: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 gears
.PHONY : gears

# fast build rule for target.
gears/fast:
	$(MAKE) $(MAKESILENT) -f Libraries/glfw-3.3.6/examples/CMakeFiles/gears.dir/build.make Libraries/glfw-3.3.6/examples/CMakeFiles/gears.dir/build
.PHONY : gears/fast

#=============================================================================
# Target rules for targets named heightmap

# Build rule for target.
heightmap: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 heightmap
.PHONY : heightmap

# fast build rule for target.
heightmap/fast:
	$(MAKE) $(MAKESILENT) -f Libraries/glfw-3.3.6/examples/CMakeFiles/heightmap.dir/build.make Libraries/glfw-3.3.6/examples/CMakeFiles/heightmap.dir/build
.PHONY : heightmap/fast

#=============================================================================
# Target rules for targets named offscreen

# Build rule for target.
offscreen: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 offscreen
.PHONY : offscreen

# fast build rule for target.
offscreen/fast:
	$(MAKE) $(MAKESILENT) -f Libraries/glfw-3.3.6/examples/CMakeFiles/offscreen.dir/build.make Libraries/glfw-3.3.6/examples/CMakeFiles/offscreen.dir/build
.PHONY : offscreen/fast

#=============================================================================
# Target rules for targets named particles

# Build rule for target.
particles: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 particles
.PHONY : particles

# fast build rule for target.
particles/fast:
	$(MAKE) $(MAKESILENT) -f Libraries/glfw-3.3.6/examples/CMakeFiles/particles.dir/build.make Libraries/glfw-3.3.6/examples/CMakeFiles/particles.dir/build
.PHONY : particles/fast

#=============================================================================
# Target rules for targets named sharing

# Build rule for target.
sharing: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 sharing
.PHONY : sharing

# fast build rule for target.
sharing/fast:
	$(MAKE) $(MAKESILENT) -f Libraries/glfw-3.3.6/examples/CMakeFiles/sharing.dir/build.make Libraries/glfw-3.3.6/examples/CMakeFiles/sharing.dir/build
.PHONY : sharing/fast

#=============================================================================
# Target rules for targets named simple

# Build rule for target.
simple: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 simple
.PHONY : simple

# fast build rule for target.
simple/fast:
	$(MAKE) $(MAKESILENT) -f Libraries/glfw-3.3.6/examples/CMakeFiles/simple.dir/build.make Libraries/glfw-3.3.6/examples/CMakeFiles/simple.dir/build
.PHONY : simple/fast

#=============================================================================
# Target rules for targets named splitview

# Build rule for target.
splitview: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 splitview
.PHONY : splitview

# fast build rule for target.
splitview/fast:
	$(MAKE) $(MAKESILENT) -f Libraries/glfw-3.3.6/examples/CMakeFiles/splitview.dir/build.make Libraries/glfw-3.3.6/examples/CMakeFiles/splitview.dir/build
.PHONY : splitview/fast

#=============================================================================
# Target rules for targets named wave

# Build rule for target.
wave: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 wave
.PHONY : wave

# fast build rule for target.
wave/fast:
	$(MAKE) $(MAKESILENT) -f Libraries/glfw-3.3.6/examples/CMakeFiles/wave.dir/build.make Libraries/glfw-3.3.6/examples/CMakeFiles/wave.dir/build
.PHONY : wave/fast

#=============================================================================
# Target rules for targets named clipboard

# Build rule for target.
clipboard: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clipboard
.PHONY : clipboard

# fast build rule for target.
clipboard/fast:
	$(MAKE) $(MAKESILENT) -f Libraries/glfw-3.3.6/tests/CMakeFiles/clipboard.dir/build.make Libraries/glfw-3.3.6/tests/CMakeFiles/clipboard.dir/build
.PHONY : clipboard/fast

#=============================================================================
# Target rules for targets named events

# Build rule for target.
events: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 events
.PHONY : events

# fast build rule for target.
events/fast:
	$(MAKE) $(MAKESILENT) -f Libraries/glfw-3.3.6/tests/CMakeFiles/events.dir/build.make Libraries/glfw-3.3.6/tests/CMakeFiles/events.dir/build
.PHONY : events/fast

#=============================================================================
# Target rules for targets named msaa

# Build rule for target.
msaa: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 msaa
.PHONY : msaa

# fast build rule for target.
msaa/fast:
	$(MAKE) $(MAKESILENT) -f Libraries/glfw-3.3.6/tests/CMakeFiles/msaa.dir/build.make Libraries/glfw-3.3.6/tests/CMakeFiles/msaa.dir/build
.PHONY : msaa/fast

#=============================================================================
# Target rules for targets named glfwinfo

# Build rule for target.
glfwinfo: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 glfwinfo
.PHONY : glfwinfo

# fast build rule for target.
glfwinfo/fast:
	$(MAKE) $(MAKESILENT) -f Libraries/glfw-3.3.6/tests/CMakeFiles/glfwinfo.dir/build.make Libraries/glfw-3.3.6/tests/CMakeFiles/glfwinfo.dir/build
.PHONY : glfwinfo/fast

#=============================================================================
# Target rules for targets named iconify

# Build rule for target.
iconify: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 iconify
.PHONY : iconify

# fast build rule for target.
iconify/fast:
	$(MAKE) $(MAKESILENT) -f Libraries/glfw-3.3.6/tests/CMakeFiles/iconify.dir/build.make Libraries/glfw-3.3.6/tests/CMakeFiles/iconify.dir/build
.PHONY : iconify/fast

#=============================================================================
# Target rules for targets named monitors

# Build rule for target.
monitors: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 monitors
.PHONY : monitors

# fast build rule for target.
monitors/fast:
	$(MAKE) $(MAKESILENT) -f Libraries/glfw-3.3.6/tests/CMakeFiles/monitors.dir/build.make Libraries/glfw-3.3.6/tests/CMakeFiles/monitors.dir/build
.PHONY : monitors/fast

#=============================================================================
# Target rules for targets named reopen

# Build rule for target.
reopen: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 reopen
.PHONY : reopen

# fast build rule for target.
reopen/fast:
	$(MAKE) $(MAKESILENT) -f Libraries/glfw-3.3.6/tests/CMakeFiles/reopen.dir/build.make Libraries/glfw-3.3.6/tests/CMakeFiles/reopen.dir/build
.PHONY : reopen/fast

#=============================================================================
# Target rules for targets named cursor

# Build rule for target.
cursor: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 cursor
.PHONY : cursor

# fast build rule for target.
cursor/fast:
	$(MAKE) $(MAKESILENT) -f Libraries/glfw-3.3.6/tests/CMakeFiles/cursor.dir/build.make Libraries/glfw-3.3.6/tests/CMakeFiles/cursor.dir/build
.PHONY : cursor/fast

#=============================================================================
# Target rules for targets named empty

# Build rule for target.
empty: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 empty
.PHONY : empty

# fast build rule for target.
empty/fast:
	$(MAKE) $(MAKESILENT) -f Libraries/glfw-3.3.6/tests/CMakeFiles/empty.dir/build.make Libraries/glfw-3.3.6/tests/CMakeFiles/empty.dir/build
.PHONY : empty/fast

#=============================================================================
# Target rules for targets named gamma

# Build rule for target.
gamma: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 gamma
.PHONY : gamma

# fast build rule for target.
gamma/fast:
	$(MAKE) $(MAKESILENT) -f Libraries/glfw-3.3.6/tests/CMakeFiles/gamma.dir/build.make Libraries/glfw-3.3.6/tests/CMakeFiles/gamma.dir/build
.PHONY : gamma/fast

#=============================================================================
# Target rules for targets named icon

# Build rule for target.
icon: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 icon
.PHONY : icon

# fast build rule for target.
icon/fast:
	$(MAKE) $(MAKESILENT) -f Libraries/glfw-3.3.6/tests/CMakeFiles/icon.dir/build.make Libraries/glfw-3.3.6/tests/CMakeFiles/icon.dir/build
.PHONY : icon/fast

#=============================================================================
# Target rules for targets named inputlag

# Build rule for target.
inputlag: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 inputlag
.PHONY : inputlag

# fast build rule for target.
inputlag/fast:
	$(MAKE) $(MAKESILENT) -f Libraries/glfw-3.3.6/tests/CMakeFiles/inputlag.dir/build.make Libraries/glfw-3.3.6/tests/CMakeFiles/inputlag.dir/build
.PHONY : inputlag/fast

#=============================================================================
# Target rules for targets named joysticks

# Build rule for target.
joysticks: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 joysticks
.PHONY : joysticks

# fast build rule for target.
joysticks/fast:
	$(MAKE) $(MAKESILENT) -f Libraries/glfw-3.3.6/tests/CMakeFiles/joysticks.dir/build.make Libraries/glfw-3.3.6/tests/CMakeFiles/joysticks.dir/build
.PHONY : joysticks/fast

#=============================================================================
# Target rules for targets named opacity

# Build rule for target.
opacity: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 opacity
.PHONY : opacity

# fast build rule for target.
opacity/fast:
	$(MAKE) $(MAKESILENT) -f Libraries/glfw-3.3.6/tests/CMakeFiles/opacity.dir/build.make Libraries/glfw-3.3.6/tests/CMakeFiles/opacity.dir/build
.PHONY : opacity/fast

#=============================================================================
# Target rules for targets named tearing

# Build rule for target.
tearing: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 tearing
.PHONY : tearing

# fast build rule for target.
tearing/fast:
	$(MAKE) $(MAKESILENT) -f Libraries/glfw-3.3.6/tests/CMakeFiles/tearing.dir/build.make Libraries/glfw-3.3.6/tests/CMakeFiles/tearing.dir/build
.PHONY : tearing/fast

#=============================================================================
# Target rules for targets named threads

# Build rule for target.
threads: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 threads
.PHONY : threads

# fast build rule for target.
threads/fast:
	$(MAKE) $(MAKESILENT) -f Libraries/glfw-3.3.6/tests/CMakeFiles/threads.dir/build.make Libraries/glfw-3.3.6/tests/CMakeFiles/threads.dir/build
.PHONY : threads/fast

#=============================================================================
# Target rules for targets named timeout

# Build rule for target.
timeout: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 timeout
.PHONY : timeout

# fast build rule for target.
timeout/fast:
	$(MAKE) $(MAKESILENT) -f Libraries/glfw-3.3.6/tests/CMakeFiles/timeout.dir/build.make Libraries/glfw-3.3.6/tests/CMakeFiles/timeout.dir/build
.PHONY : timeout/fast

#=============================================================================
# Target rules for targets named title

# Build rule for target.
title: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 title
.PHONY : title

# fast build rule for target.
title/fast:
	$(MAKE) $(MAKESILENT) -f Libraries/glfw-3.3.6/tests/CMakeFiles/title.dir/build.make Libraries/glfw-3.3.6/tests/CMakeFiles/title.dir/build
.PHONY : title/fast

#=============================================================================
# Target rules for targets named triangle-vulkan

# Build rule for target.
triangle-vulkan: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 triangle-vulkan
.PHONY : triangle-vulkan

# fast build rule for target.
triangle-vulkan/fast:
	$(MAKE) $(MAKESILENT) -f Libraries/glfw-3.3.6/tests/CMakeFiles/triangle-vulkan.dir/build.make Libraries/glfw-3.3.6/tests/CMakeFiles/triangle-vulkan.dir/build
.PHONY : triangle-vulkan/fast

#=============================================================================
# Target rules for targets named windows

# Build rule for target.
windows: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 windows
.PHONY : windows

# fast build rule for target.
windows/fast:
	$(MAKE) $(MAKESILENT) -f Libraries/glfw-3.3.6/tests/CMakeFiles/windows.dir/build.make Libraries/glfw-3.3.6/tests/CMakeFiles/windows.dir/build
.PHONY : windows/fast

src/engine/graphics/Camera.o: src/engine/graphics/Camera.cpp.o
.PHONY : src/engine/graphics/Camera.o

# target to build an object file
src/engine/graphics/Camera.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Racingmaybe.dir/build.make CMakeFiles/Racingmaybe.dir/src/engine/graphics/Camera.cpp.o
.PHONY : src/engine/graphics/Camera.cpp.o

src/engine/graphics/Camera.i: src/engine/graphics/Camera.cpp.i
.PHONY : src/engine/graphics/Camera.i

# target to preprocess a source file
src/engine/graphics/Camera.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Racingmaybe.dir/build.make CMakeFiles/Racingmaybe.dir/src/engine/graphics/Camera.cpp.i
.PHONY : src/engine/graphics/Camera.cpp.i

src/engine/graphics/Camera.s: src/engine/graphics/Camera.cpp.s
.PHONY : src/engine/graphics/Camera.s

# target to generate assembly for a file
src/engine/graphics/Camera.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Racingmaybe.dir/build.make CMakeFiles/Racingmaybe.dir/src/engine/graphics/Camera.cpp.s
.PHONY : src/engine/graphics/Camera.cpp.s

src/engine/graphics/GameObject.o: src/engine/graphics/GameObject.cpp.o
.PHONY : src/engine/graphics/GameObject.o

# target to build an object file
src/engine/graphics/GameObject.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Racingmaybe.dir/build.make CMakeFiles/Racingmaybe.dir/src/engine/graphics/GameObject.cpp.o
.PHONY : src/engine/graphics/GameObject.cpp.o

src/engine/graphics/GameObject.i: src/engine/graphics/GameObject.cpp.i
.PHONY : src/engine/graphics/GameObject.i

# target to preprocess a source file
src/engine/graphics/GameObject.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Racingmaybe.dir/build.make CMakeFiles/Racingmaybe.dir/src/engine/graphics/GameObject.cpp.i
.PHONY : src/engine/graphics/GameObject.cpp.i

src/engine/graphics/GameObject.s: src/engine/graphics/GameObject.cpp.s
.PHONY : src/engine/graphics/GameObject.s

# target to generate assembly for a file
src/engine/graphics/GameObject.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Racingmaybe.dir/build.make CMakeFiles/Racingmaybe.dir/src/engine/graphics/GameObject.cpp.s
.PHONY : src/engine/graphics/GameObject.cpp.s

src/engine/graphics/Renderer.o: src/engine/graphics/Renderer.cpp.o
.PHONY : src/engine/graphics/Renderer.o

# target to build an object file
src/engine/graphics/Renderer.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Racingmaybe.dir/build.make CMakeFiles/Racingmaybe.dir/src/engine/graphics/Renderer.cpp.o
.PHONY : src/engine/graphics/Renderer.cpp.o

src/engine/graphics/Renderer.i: src/engine/graphics/Renderer.cpp.i
.PHONY : src/engine/graphics/Renderer.i

# target to preprocess a source file
src/engine/graphics/Renderer.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Racingmaybe.dir/build.make CMakeFiles/Racingmaybe.dir/src/engine/graphics/Renderer.cpp.i
.PHONY : src/engine/graphics/Renderer.cpp.i

src/engine/graphics/Renderer.s: src/engine/graphics/Renderer.cpp.s
.PHONY : src/engine/graphics/Renderer.s

# target to generate assembly for a file
src/engine/graphics/Renderer.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Racingmaybe.dir/build.make CMakeFiles/Racingmaybe.dir/src/engine/graphics/Renderer.cpp.s
.PHONY : src/engine/graphics/Renderer.cpp.s

src/engine/io/Window.o: src/engine/io/Window.cpp.o
.PHONY : src/engine/io/Window.o

# target to build an object file
src/engine/io/Window.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Racingmaybe.dir/build.make CMakeFiles/Racingmaybe.dir/src/engine/io/Window.cpp.o
.PHONY : src/engine/io/Window.cpp.o

src/engine/io/Window.i: src/engine/io/Window.cpp.i
.PHONY : src/engine/io/Window.i

# target to preprocess a source file
src/engine/io/Window.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Racingmaybe.dir/build.make CMakeFiles/Racingmaybe.dir/src/engine/io/Window.cpp.i
.PHONY : src/engine/io/Window.cpp.i

src/engine/io/Window.s: src/engine/io/Window.cpp.s
.PHONY : src/engine/io/Window.s

# target to generate assembly for a file
src/engine/io/Window.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Racingmaybe.dir/build.make CMakeFiles/Racingmaybe.dir/src/engine/io/Window.cpp.s
.PHONY : src/engine/io/Window.cpp.s

src/engine/utils/Timer.o: src/engine/utils/Timer.cpp.o
.PHONY : src/engine/utils/Timer.o

# target to build an object file
src/engine/utils/Timer.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Racingmaybe.dir/build.make CMakeFiles/Racingmaybe.dir/src/engine/utils/Timer.cpp.o
.PHONY : src/engine/utils/Timer.cpp.o

src/engine/utils/Timer.i: src/engine/utils/Timer.cpp.i
.PHONY : src/engine/utils/Timer.i

# target to preprocess a source file
src/engine/utils/Timer.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Racingmaybe.dir/build.make CMakeFiles/Racingmaybe.dir/src/engine/utils/Timer.cpp.i
.PHONY : src/engine/utils/Timer.cpp.i

src/engine/utils/Timer.s: src/engine/utils/Timer.cpp.s
.PHONY : src/engine/utils/Timer.s

# target to generate assembly for a file
src/engine/utils/Timer.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Racingmaybe.dir/build.make CMakeFiles/Racingmaybe.dir/src/engine/utils/Timer.cpp.s
.PHONY : src/engine/utils/Timer.cpp.s

src/gl.o: src/gl.c.o
.PHONY : src/gl.o

# target to build an object file
src/gl.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Racingmaybe.dir/build.make CMakeFiles/Racingmaybe.dir/src/gl.c.o
.PHONY : src/gl.c.o

src/gl.i: src/gl.c.i
.PHONY : src/gl.i

# target to preprocess a source file
src/gl.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Racingmaybe.dir/build.make CMakeFiles/Racingmaybe.dir/src/gl.c.i
.PHONY : src/gl.c.i

src/gl.s: src/gl.c.s
.PHONY : src/gl.s

# target to generate assembly for a file
src/gl.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Racingmaybe.dir/build.make CMakeFiles/Racingmaybe.dir/src/gl.c.s
.PHONY : src/gl.c.s

src/main/Game.o: src/main/Game.cpp.o
.PHONY : src/main/Game.o

# target to build an object file
src/main/Game.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Racingmaybe.dir/build.make CMakeFiles/Racingmaybe.dir/src/main/Game.cpp.o
.PHONY : src/main/Game.cpp.o

src/main/Game.i: src/main/Game.cpp.i
.PHONY : src/main/Game.i

# target to preprocess a source file
src/main/Game.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Racingmaybe.dir/build.make CMakeFiles/Racingmaybe.dir/src/main/Game.cpp.i
.PHONY : src/main/Game.cpp.i

src/main/Game.s: src/main/Game.cpp.s
.PHONY : src/main/Game.s

# target to generate assembly for a file
src/main/Game.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Racingmaybe.dir/build.make CMakeFiles/Racingmaybe.dir/src/main/Game.cpp.s
.PHONY : src/main/Game.cpp.s

src/scenes/SceneEnvir.o: src/scenes/SceneEnvir.cpp.o
.PHONY : src/scenes/SceneEnvir.o

# target to build an object file
src/scenes/SceneEnvir.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Racingmaybe.dir/build.make CMakeFiles/Racingmaybe.dir/src/scenes/SceneEnvir.cpp.o
.PHONY : src/scenes/SceneEnvir.cpp.o

src/scenes/SceneEnvir.i: src/scenes/SceneEnvir.cpp.i
.PHONY : src/scenes/SceneEnvir.i

# target to preprocess a source file
src/scenes/SceneEnvir.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Racingmaybe.dir/build.make CMakeFiles/Racingmaybe.dir/src/scenes/SceneEnvir.cpp.i
.PHONY : src/scenes/SceneEnvir.cpp.i

src/scenes/SceneEnvir.s: src/scenes/SceneEnvir.cpp.s
.PHONY : src/scenes/SceneEnvir.s

# target to generate assembly for a file
src/scenes/SceneEnvir.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Racingmaybe.dir/build.make CMakeFiles/Racingmaybe.dir/src/scenes/SceneEnvir.cpp.s
.PHONY : src/scenes/SceneEnvir.cpp.s

src/scenes/SceneHandler.o: src/scenes/SceneHandler.cpp.o
.PHONY : src/scenes/SceneHandler.o

# target to build an object file
src/scenes/SceneHandler.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Racingmaybe.dir/build.make CMakeFiles/Racingmaybe.dir/src/scenes/SceneHandler.cpp.o
.PHONY : src/scenes/SceneHandler.cpp.o

src/scenes/SceneHandler.i: src/scenes/SceneHandler.cpp.i
.PHONY : src/scenes/SceneHandler.i

# target to preprocess a source file
src/scenes/SceneHandler.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Racingmaybe.dir/build.make CMakeFiles/Racingmaybe.dir/src/scenes/SceneHandler.cpp.i
.PHONY : src/scenes/SceneHandler.cpp.i

src/scenes/SceneHandler.s: src/scenes/SceneHandler.cpp.s
.PHONY : src/scenes/SceneHandler.s

# target to generate assembly for a file
src/scenes/SceneHandler.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Racingmaybe.dir/build.make CMakeFiles/Racingmaybe.dir/src/scenes/SceneHandler.cpp.s
.PHONY : src/scenes/SceneHandler.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... install"
	@echo "... install/local"
	@echo "... install/strip"
	@echo "... list_install_components"
	@echo "... rebuild_cache"
	@echo "... uninstall"
	@echo "... update_mappings"
	@echo "... Racingmaybe"
	@echo "... boing"
	@echo "... clipboard"
	@echo "... cursor"
	@echo "... empty"
	@echo "... events"
	@echo "... gamma"
	@echo "... gears"
	@echo "... glfw"
	@echo "... glfwinfo"
	@echo "... heightmap"
	@echo "... icon"
	@echo "... iconify"
	@echo "... inputlag"
	@echo "... joysticks"
	@echo "... monitors"
	@echo "... msaa"
	@echo "... offscreen"
	@echo "... opacity"
	@echo "... particles"
	@echo "... reopen"
	@echo "... sharing"
	@echo "... simple"
	@echo "... splitview"
	@echo "... tearing"
	@echo "... threads"
	@echo "... timeout"
	@echo "... title"
	@echo "... triangle-vulkan"
	@echo "... wave"
	@echo "... windows"
	@echo "... src/engine/graphics/Camera.o"
	@echo "... src/engine/graphics/Camera.i"
	@echo "... src/engine/graphics/Camera.s"
	@echo "... src/engine/graphics/GameObject.o"
	@echo "... src/engine/graphics/GameObject.i"
	@echo "... src/engine/graphics/GameObject.s"
	@echo "... src/engine/graphics/Renderer.o"
	@echo "... src/engine/graphics/Renderer.i"
	@echo "... src/engine/graphics/Renderer.s"
	@echo "... src/engine/io/Window.o"
	@echo "... src/engine/io/Window.i"
	@echo "... src/engine/io/Window.s"
	@echo "... src/engine/utils/Timer.o"
	@echo "... src/engine/utils/Timer.i"
	@echo "... src/engine/utils/Timer.s"
	@echo "... src/gl.o"
	@echo "... src/gl.i"
	@echo "... src/gl.s"
	@echo "... src/main/Game.o"
	@echo "... src/main/Game.i"
	@echo "... src/main/Game.s"
	@echo "... src/scenes/SceneEnvir.o"
	@echo "... src/scenes/SceneEnvir.i"
	@echo "... src/scenes/SceneEnvir.s"
	@echo "... src/scenes/SceneHandler.o"
	@echo "... src/scenes/SceneHandler.i"
	@echo "... src/scenes/SceneHandler.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

