package audio;

public enum SfxTypes {

	REGULAR_PRESS, REGULAR_HOVER, READY, UNREADY, BUY, BUY_FAILED, 
	REDLIGHT, GREENLIGHT, COUNTDOWN, START, OPEN_STORE, CLOSE_STORE, JOINED, LEFT,
	CHAT, NEW_BONUS, CANCEL_BONUS, START_ENGINE, WON, LOST, WHOOSH, LOSTLIFE, GOLD_BONUS, NORMAL_BONUS, UNLOCKED
}
